### ISSUE TITLE
Nickauth "Forgets Nicks"

### ISSUE THREAD

**Issue by cookta2012** [ProgVal/Limnoria#1206] opened 2016-01-11 04:58 UTC
It for gets in the sense it doesnt load the nicks on file into memory, im using python 2.7

**Comment by Mikaela** [comment] 2016-01-11 05:08
This is either `supybot.followIdentificationThroughNickChanges` or duplicate of https://github.com/ProgVal/Limnoria/issues/1143.

**Comment by cookta2012** [comment] 2016-01-11 10:11
I updated python to 3.4, and when i add the network name now i do it all in lowercase, it looks like it works now

**Comment by ProgVal** [comment] 2016-01-11 10:13
It's nice that it works now (and that you updated to Python 3 too), but I don't think that can be the reason the issue was fixed

**Comment by cookta2012** [comment] 2016-01-11 21:10
it could have also been the fact i was using caps all i can think

**Closed** 2016-02-07 10:07 UTC
