### ISSUE TITLE
Supy stalls or gets stuck on exit.

### ISSUE THREAD

**Issue by weedy** [ProgVal/Limnoria#432] opened 2012-12-08 03:16 UTC
Not entirely sure what it's doing here.

```
stat64("/home/weedy/supybot/data/tmp/Seen.db.4ac589448a120bc56771fb7c04c0dd3cdd4a4a25", {st_mode=S_IFREG|0644, st_size=3588643, ...}) = 0
stat64("/home/weedy/supybot/data/Seen.db", {st_mode=S_IFREG|0644, st_size=3588984, ...}) = 0
stat64("/home/weedy/supybot/data/Seen.db", {st_mode=S_IFREG|0644, st_size=3588984, ...}) = 0
open("/home/weedy/supybot/data/Seen.db", O_WRONLY|O_CREAT|O_APPEND|O_LARGEFILE, 0666) = 3
fstat64(3, {st_mode=S_IFREG|0644, st_size=3588984, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb7157000
fstat64(3, {st_mode=S_IFREG|0644, st_size=3588984, ...}) = 0
_llseek(3, 3588984, [3588984], SEEK_SET) = 0
fstat64(3, {st_mode=S_IFREG|0644, st_size=3588984, ...}) = 0
close(3)                                = 0
munmap(0xb7157000, 4096)                = 0
stat64("/home/weedy/supybot/data/Seen.db", {st_mode=S_IFREG|0644, st_size=3588984, ...}) = 0
rename("/home/weedy/supybot/data/tmp/Seen.db.4ac589448a120bc56771fb7c04c0dd3cdd4a4a25", "/home/weedy/supybot/data/Seen.db") = 0

WARNING 2012-12-07T22:12:47 Disconnect from irc.sxci.net:9999: error: [Errno 9] Bad file descriptor.
INFO 2012-12-07T22:12:47 Reconnecting to rizon at 2012-12-07T22:12:57.
DEBUG 2012-12-07T22:12:47 Outgoing message (irchighway): QUIT :SmugLeaf
INFO 2012-12-07T22:12:47 Driver for Irc object for irchighway dying.
INFO 2012-12-07T22:12:47 Irc object for irchighway dying.
INFO 2012-12-07T22:12:47 Driver for Irc object for irchighway dying.
```

**Comment by GLolol** [comment] 2017-09-20 01:50
This looks like a duplicate of #450. Closing in favour of that issue which has more follow-up information

**Closed by GLolol** 2017-09-20 01:50 UTC
Labels: Bug
