### ISSUE TITLE
Herald: config parameters do not applying to default herald

### ISSUE THREAD

**Issue by koobs** [ProgVal/Limnoria#1372] opened 2019-10-05 09:49 UTC
As investigated with @ProgVal on freenode, _at least_ Herald config's `throttle` and `throttle.afterPart` don't apply to the **default** herald, when they should. It's probable that `afterSplit` and other configs are also affected.

Current behaviour:

Cycling the channel, after setting `throttle` or `afterPart`, results in herald messaging (heralding) the user multiple times.

Expected behaviour:

Herald does **not** send the default herald message to a user if/when  `throttle` or `throttle.afterPart` (or `afterSplit`) are set/matched for that user.

**Comment by lsalvadore** [comment] 2020-01-24 19:31
Just a guess.

I think the problem is in line 119 and line 123 of Herald/plugin.py: ` if now - self.lastHerald.get((channel, id), 0) > throttle:` and `if now - self.lastParts[channel, id] < i:`.
You calculate the differences `now - self.lastHerald.get((channel, id), 0)` and `now - self.lastParts[channel, id]`, which, when a user cycles the channel, are extremely small values: extremely small values often mess up codes.
In your case these extremely small values are then compared with `throttle` and `throttle.afterPart`, which are defined in config.py as `PositiveInteger` and `NonNegativeInteger` respectively. I do not know how types and conversions are implemented in Limnoria, but I guess the extremely small value is converted to PositiveInteger and NonNegativeInteger in such a way that it becomes an extremely high value. Do you think it is possible?

If conversion of extremely small values is indeed the problem, explicit conversion would probably do the trick, i.e. substituing the lines with `if int(now - self.lastHerald.get((channel, id), 0)) > throttle:` and `if int(now - self.lastParts[channel, id]) < i:`.

**Comment by lsalvadore** [comment] 2020-01-26 17:29
It has been pointed out that the bug concerns the default hearld only, not all heralds (I missed that part in the OP), so my guess is probably wrong.
I am sorry, I will try to study better the plugin.

**Comment by koobs** [comment] 2020-07-03 03:07
@ProgVal Hey mate :) We've been blocked on this issue since reporting, to making substantial changes to our bot for #freebsd* (> 50) channels on freenode. I'm trying to find someone in the community to resolve this, but if you have spare cycles or are otherwise able to prioritize this one, provide guidance on resolution (so we can more easily submit a PR) or know of people in the Limnoria community who might be able to assist, that would be greatly apprecisted

**Comment by Freaky** [comment] 2020-07-03 18:57
Those `time.time()` calls look like they should be `time.monotonic()`, so throttling isn't broken by system clock changes.

**Comment by ProgVal** [comment] 2020-07-03 19:01
@Freaky Indeed. Fixed in 76edd3189c8851d48f55d6f765b2a2ec65372566

**Closed** 2020-08-30 08:06 UTC
Labels: Bug
