### ISSUE TITLE
Error if pipe in nick

### ISSUE THREAD

**Issue by 2mac** [ProgVal/Limnoria#1006] opened 2015-01-16 22:18 UTC
If a command repeats something with a user's name and that username contains a pipe character, the function will either fail (if after the pipe is not a command) or execute unwanted operations (if after the pipe is a valid command.

**Comment by GLolol** [comment] 2015-01-17 01:11
Are you talking about using pipes for nested commands? I'm confused.

**Comment by 2mac** [comment] 2015-01-17 01:20
A bot has a command which addresses the calling user's name in its response. If that user's name has a pipe character in it, the command will either fail or call unwanted code.

**Comment by GLolol** [comment] 2015-01-17 01:36
Unless you have `commands.nested.pipeSyntax` turned on, a pipe is just a normal character and has no effect. 

I also cannot reproduce this error. When a command's arguments are properly escaped (using `"quoted text | works fine"`) or you're just displaying the output of another command, that should not trigger any nesting at all.

What *exact* commands are you running?

**Comment by 2mac** [comment] 2015-01-17 01:51
This particular bot (it's not mine) has !why. The !why command causes the bot to say (into chat) "Because, <USER>, ...". After that, some humorous reason why something might happen.

**Comment by GLolol** [comment] 2015-01-17 02:32
I'm pretty sure that's not a built in command anywhere in stock Limnoria. Can you paste the output of `!help why`?

**Comment by 2mac** [comment] 2015-01-17 03:46
`<Zerock> !help why`

`<phrik> Zerock: (why <an alias, 0 arguments>) -- Alias for "echo Because, $nick, [excuse]".`

**Comment by GLolol** [comment] 2015-01-17 03:53
I can't reproduce the behavior you're describing.

**Comment by 2mac** [comment] 2015-01-17 03:59
I have sent an e-mail to the address on your account disclosing the bot instance. I will not put it in public here for privacy reasons for the ones running the bot.

**Comment by ProgVal** [comment] 2015-01-17 07:22
@2mac Are you sure `commands.nested.pipeSyntax` is off?

**Comment by 2mac** [comment] 2015-01-17 13:57
As I'm not the owner of the instance, I could not tell you. Do you think it is a configuration issue that I can report to the owner?

**Comment by ProgVal** [comment] 2015-01-17 14:10
You don't haveto be an owner to get the value of this variable.

**Comment by Mikaela** [comment] 2015-01-17 14:54
http://doc.supybot.aperio.fr/en/latest/use/configuration.html#configuration-values

**Comment by GLolol** [comment] 2015-01-17 18:03
These people are ridiculously paranoid about their bot names :)

```
<tacocat> !config commands.nested.pipeSyntax
<redacted> tacocat: Global: True; #<redacted>: True
<tacocat> !version
<redacted> tacocat: The current (running) version of this Supybot is 0.83.4.1+limnoria installed on 2015-01-10T20-22-06, running on Python 3.4.2 (default, Jan 12 2015, 11:38:40)  [GCC 4.9.2 20141224 (prerelease)].  The newest versions available online are 2015.01.17 (in testing), 2014.12.22 (in master).
```

`commands.nested.pipeSyntax` is on, but I can't reproduce myself the behavior @2mac is describing when I turn it on for my own bots.

**Comment by ProgVal** [comment] 2015-02-22 09:46
Should I close this issue?

**Comment by Mikaela** [comment] 2015-02-22 09:59
I think that this issue is invalid based on https://github.com/ProgVal/Limnoria/issues/1006#issuecomment-70377088.

**Closed** 2015-07-08 09:25 UTC
Labels: Bug
